In [70]:
import glob
import os
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
All_games = pd.read_csv('Data/All_games.csv')
All_games.drop('Unnamed: 0', axis= 1, inplace= True)
All_games

Game    Attendance  Total_goals  goals_diff  \
0        ADO Den Haag vs AZ Alkmaar  12125.333333            3           1   
1              ADO Den Haag vs Ajax  14013.833333            2           1   
2           ADO Den Haag vs Cambuur  10181.500000            3           1   
3     ADO Den Haag vs De Graafschap  10808.500000            3           0   
4         ADO Den Haag vs Dordrecht  11023.000000            2           2   
...                             ...           ...          ...         ...   
6506               Zwolle vs Twente  12555.750000            2           1   
6507              Zwolle vs Utrecht  12064.428571            2           0   
6508            Zwolle vs VVV-Venlo  13087.000000            2           0   
6509              Zwolle vs Vitesse  11623.750000            3           1   
6510            Zwolle vs Willem II  12622.666667            2           1   

            Game_Class League  
0     Competitive_Game      D  
1          Closed_Game      D  
2     Competitive_Game      D  
3     Competitive_Game      D  
4     Competitive_Game      D  
...                ...    ...  
6506       Closed_Game      D  
6507       Closed_Game      D  
6508       Closed_Game      D  
6509  Competitive_Game      D  
6510       Closed_Game      D  

[6511 rows x 6 columns]

In [72]:
# input games to reccomend from
# for example the games of 12 and 13 march
today = ['Brighton vs Liverpool', 'Brentford vs Burnley', 'Manchester Utd vs Tottenham',
'Hoffenheim vs Bayern Munich','Union Berlin vs Stuttgart', 'Augsburg vs Mainz 05', 'Freiburg vs Wolfsburg', 
'Levante vs Espanyol', 'Granada vs Elche', 'Villarreal vs Celta Vigo', 'Getafe vs Valencia', 'Al-Hazem vs Damac',
'AS Saint-Étienne vs Lyon']
Tomorrow = ['Leeds United vs Norwich City', 'Chelsea vs Newcastle Utd', 'West Ham vs Aston Villa',
'Southampton vs Watford','Everton vs Wolves', 'Arsenal vs Leicester City', 'Barcelona vs Osasuna', 
'Real Sociedad vs Alavés', 'Betis vs Athletic Club', 'Dortmund vs Arminia', 'Leverkusen vs Köln', 'Al-Raed vs Al-Hilal',
'Al-Shabab vs Al-Ittihad', 'Paris S-G vs Bordeaux', 'Bres vs Marseille', 'Milan vs Empoli', 'Fiorentina vs Bologna', 
'Torino vs Inter', 'Lazio vs Venezia', 'Sampdoria vs Juventus', 'Hellas Verona vs Napoli', 'Udinese vs Roma']


In [73]:
All_games2 = pd.DataFrame()
def inputgame(d):
    global All_games2
    for i in range(len(d)):
        All_games2=  All_games2.append(All_games[All_games['Game'].str.contains(d[i])])
    return All_games2.reset_index(drop= True, inplace=True)

In [74]:
inputgame(Tomorrow)
All_games=All_games2

In [75]:
All_games['id'] = All_games.groupby(['Game']).ngroup()
All_games

Game    Attendance  Total_goals  goals_diff  \
0    Chelsea vs Newcastle Utd  41155.200000            2           2   
1     West Ham vs Aston Villa  34885.500000            1           0   
2      Southampton vs Watford  29280.800000            2           1   
3           Everton vs Wolves  27914.000000            3           1   
4   Arsenal vs Leicester City  59828.600000            3           1   
5        Barcelona vs Osasuna  63989.000000            6           5   
6     Real Sociedad vs Alavés  24205.000000            2           2   
7      Betis vs Athletic Club  40053.000000            2           1   
8         Dortmund vs Arminia           NaN            3           3   
9          Leverkusen vs Köln  30210.000000            4           2   
10        Al-Raed vs Al-Hilal   8774.000000            2           2   
11    Al-Shabab vs Al-Ittihad   5896.833333            3           1   
12      Paris S-G vs Bordeaux  46426.166667            3           1   
13            Milan vs Empoli  37236.750000            2           1   
14      Fiorentina vs Bologna  26444.250000            1           1   
15            Torino vs Inter  25210.333333            2           1   
16      Sampdoria vs Juventus  24668.666667            2           1   
17    Hellas Verona vs Napoli  18388.666667            2           2   
18            Udinese vs Roma  15844.857143            1           1   

               Game_Class League  id  
0        Competitive_Game     PL   5  
1             Closed_Game     PL  18  
2             Closed_Game     PL  15  
3        Competitive_Game     PL   7  
4        Competitive_Game     PL   2  
5           One_Side_Game     SP   3  
6        Competitive_Game     SP  13  
7             Closed_Game     SP   4  
8           One_Side_Game     BL   6  
9   Competitive_Open_Game     BL  10  
10       Competitive_Game    SPL   0  
11       Competitive_Game    SPL   1  
12       Competitive_Game     FL  12  
13            Closed_Game     IT  11  
14            Closed_Game     IT   8  
15            Closed_Game     IT  16  
16            Closed_Game     IT  14  
17       Competitive_Game     IT   9  
18            Closed_Game     IT  17

In [76]:
features = ['Game', 'Attendance', 'Total_goals', 'goals_diff', 'Game_Class', 'League']
for feature in features:
    All_games[feature] = All_games[feature].fillna('')

In [77]:
All_games.Attendance = All_games.Attendance.astype(str)
All_games.Total_goals = All_games.Total_goals.astype(str)
All_games.goals_diff = All_games.goals_diff.astype(str)

In [78]:
def combined_features(row):
    return row['Game_Class'] +" "+row['Attendance']+" "+row['Total_goals']+" "+row['goals_diff']+" "+row['League']
All_games["combined_features"] = All_games.apply(combined_features, axis =1)

In [79]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [80]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(All_games["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0

In [81]:
cosine_sim = cosine_similarity(count_matrix)

In [82]:
game_user_likes = "Al-Shabab vs Al-Ittihad"
def get_index_from_title(Game):
    return All_games[All_games.Game == Game]['id'].values[0]
game_index = get_index_from_title(game_user_likes)

In [83]:
similar_games = list(enumerate(cosine_sim[game_index]))


In [84]:
sorted_similar_games = sorted(similar_games, key=lambda x:x[1], reverse=True)

In [85]:
sorted_similar_games

[(1, 1.0000000000000002),
 (2, 0.6666666666666669),
 (0, 0.3333333333333334),
 (3, 0.3333333333333334),
 (4, 0.3333333333333334),
 (7, 0.3333333333333334),
 (13, 0.2886751345948129),
 (14, 0.2886751345948129),
 (15, 0.2886751345948129),
 (16, 0.2886751345948129),
 (18, 0.2886751345948129),
 (5, 0.0),
 (6, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.0),
 (12, 0.0),
 (17, 0.0)]

In [86]:
def get_title_from_index(id):
    return All_games[All_games.id == id]["Game"].values[0]
i=0
for game in sorted_similar_games:
    print(get_title_from_index(game[0]))
    i=i+1
    if i>6:
        break

Al-Shabab vs Al-Ittihad
Arsenal vs Leicester City
Al-Raed vs Al-Hilal
Barcelona vs Osasuna
Betis vs Athletic Club
Everton vs Wolves
Real Sociedad vs Alavés
